"""empty message

Revision ID: 01e7e9d5a79f
Revises: 
Create Date: 2021-01-14 13:46:29.074949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01e7e9d5a79f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_user', sa.Column('name', sa.String(length=40), nullable=True))
    op.add_column('admin_user', sa.Column('surname', sa.String(length=40), nullable=True))
    op.add_column('reservation', sa.Column('author', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'author')
    op.drop_column('admin_user', 'surname')
    op.drop_column('admin_user', 'name')
    # ### end Alembic commands ###
