"""empty message

Revision ID: 06cc8698eca5
Revises: 781fadfa68b4
Create Date: 2023-06-28 15:43:55.010186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06cc8698eca5'
down_revision = '781fadfa68b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation_queue_view_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.Time()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation_queue_view_log', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
