"""empty message

Revision ID: 07fa70431171
Revises: a1a91210100b
Create Date: 2024-04-15 18:57:19.306978

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '07fa70431171'
down_revision = 'a1a91210100b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.Enum('М', 'Ж', name='genderenum')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
