"""empty message

Revision ID: 104ed1421eac
Revises: c39f6085e330
Create Date: 2024-01-19 17:52:40.877520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104ed1421eac'
down_revision = 'c39f6085e330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation_queue', schema=None) as batch_op:
        batch_op.alter_column('created_at_datetime', new_column_name="created_at")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation_queue', schema=None) as batch_op:
        batch_op.alter_column('created_at', new_column_name="created_at_datetime")

    # ### end Alembic commands ###
