"""empty message

Revision ID: 177798ad5ad1
Revises: 0662d67b0e4c
Create Date: 2024-04-22 14:53:50.110601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177798ad5ad1'
down_revision = '0662d67b0e4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_changes_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('old', sa.Text(), nullable=True),
    sa.Column('new', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], name='guest_id'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guest_changes_logs'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guest_changes_logs')
    # ### end Alembic commands ###
