"""empty message

Revision ID: 271e43fe478b
Revises: f9c0e8af2ff0
Create Date: 2023-06-16 14:56:25.132681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '271e43fe478b'
down_revision = 'f9c0e8af2ff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue_user',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('queue_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['queue_id'], ['reservation_queue.id'], name='queue_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queue_user')
    # ### end Alembic commands ###
