"""Добавит флаг на закрытие кинотеатра

Revision ID: 37eb6b94d763
Revises: 46ebad50319c
Create Date: 2025-03-14 17:57:03.842041

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '37eb6b94d763'
down_revision = '46ebad50319c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cinema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closed', sa.Boolean(), nullable=True))

    op.execute("UPDATE cinema SET closed = false where id != 3")
    op.execute("UPDATE cinema SET closed = true where id = 3")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cinema', schema=None) as batch_op:
        batch_op.drop_column('closed')

    # ### end Alembic commands ###
