"""empty message

Revision ID: 46ebad50319c
Revises: 903546ba71a2
Create Date: 2024-08-02 12:25:26.792060

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '46ebad50319c'
down_revision = '903546ba71a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('payment_url')

    # ### end Alembic commands ###
