"""empty message

Revision ID: 510074d70f36
Revises: 2f04ac2ba229
Create Date: 2024-01-19 17:34:34.904095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510074d70f36'
down_revision = '2f04ac2ba229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.VARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###
