"""empty message

Revision ID: 512b07381b4d
Revises: 7a2a9c1584e4
Create Date: 2022-11-18 12:59:36.662238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '512b07381b4d'
down_revision = '7a2a9c1584e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cash', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.drop_column('cash')
        batch_op.drop_column('card')

    # ### end Alembic commands ###
