"""empty message

Revision ID: 674d6e00c366
Revises: 9af7b8c48d40
Create Date: 2024-01-26 13:32:09.800129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674d6e00c366'
down_revision = '9af7b8c48d40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        pass
    # ### end Alembic commands ###
