"""empty message

Revision ID: 781fadfa68b4
Revises: a8e7dce831fc
Create Date: 2023-06-28 15:05:09.460700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781fadfa68b4'
down_revision = 'a8e7dce831fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation_queue', schema=None) as batch_op:
        batch_op.drop_constraint('reservation_id', type_='foreignkey')
        batch_op.drop_column('reservation_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reservation_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('reservation_id', 'reservation', ['reservation_id'], ['id'])

    # ### end Alembic commands ###
