"""empty message

Revision ID: 903546ba71a2
Revises: d5d4c3393343
Create Date: 2024-06-26 13:11:12.166328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '903546ba71a2'
down_revision = 'd5d4c3393343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_changes_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('old', sa.Text(), nullable=True),
    sa.Column('new', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], name='transaction_id'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction_changes_log'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_changes_log')
    # ### end Alembic commands ###
