"""Добавит таблицу с городами и их часовыми поясами

Revision ID: 938d3c9182b0
Revises: c8baa9b61842
Create Date: 2024-05-16 17:55:17.775361

"""
from alembic import op
import sqlalchemy as sa

from models import Cinema

# revision identifiers, used by Alembic.
revision = '938d3c9182b0'
down_revision = 'c8baa9b61842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('timezone', sa.String(length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_city'))
                    )
    with op.batch_alter_table('cinema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_cinema_city_id_city'), 'city', ['city_id'], ['id'])

    op.execute("""
        INSERT INTO city (name, timezone) VALUES 
        ('Москва', '+00:00'),
        ('Санкт-Петербург', '+00:00'),
        ('Казань', '+00:00'),
        ('Новосибирск', '+04:00'),
        ('Екатеринбург', '+02:00'),
        ('Нижний Новгород', '+00:00'),
        ('Челябинск', '+02:00'),
        ('Самара', '+01:00'),
        ('Омск', '+03:00'),
        ('Ростов-на-Дону', '+00:00'),
        ('Уфа', '+02:00'),
        ('Красноярск', '+04:00'),
        ('Пермь', '+02:00'),
        ('Воронеж', '+00:00'),
        ('Волгоград', '+00:00'),
        ('Краснодар', '+00:00'),
        ('Саратов', '+01:00'),
        ('Тюмень', '+02:00'),
        ('Иркутск', '+05:00'),
        ('Хабаровск', '+07:00'),
        ('Владивосток', '+07:00'),
        ('Махачкала', '+00:00'),
        ('Томск', '+04:00'),
        ('Кемерово', '+04:00'),
        ('Новокузнецк', '+04:00'),
        ('Рязань', '+00:00'),
        ('Астрахань', '+01:00'),
        ('Пенза', '+00:00'),
        ('Калининград', '-01:00'),
        ('Липецк', '+00:00'),
        ('Тула', '+00:00'),
        ('Киров', '+00:00'),
        ('Чебоксары', '+00:00'),
        ('Курск', '+00:00'),
        ('Ульяновск', '+01:00'),
        ('Ярославль', '+00:00'),
        ('Барнаул', '+04:00'),
        ('Ижевск', '+01:00'),
        ('Тверь', '+00:00'),
        ('Магнитогорск', '+02:00'),
        ('Брянск', '+00:00'),
        ('Сочи', '+00:00'),
        ('Белгород', '+00:00'),
        ('Сургут', '+02:00'),
        ('Владимир', '+00:00'),
        ('Архангельск', '+00:00'),
        ('Смоленск', '+00:00'),
        ('Мурманск', '+00:00'),
        ('Чита', '+06:00'),
        ('Саранск', '+00:00'),
        ('Калуга', '+00:00'),
        ('Якутск', '+06:00'),
        ('Севастополь', '+00:00'),
        ('Биробиджан', '+07:00'),
        ('Петропавловск-Камчатский', '+09:00');
        """)

    op.execute(sa.update(Cinema).where(Cinema.id == 1).values(city_id=49))
    op.execute(sa.update(Cinema).where(Cinema.id == 2).values(city_id=49))
    op.execute(sa.update(Cinema).where(Cinema.id == 3).values(city_id=12))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cinema', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cinema_city_id_city'), type_='foreignkey')
        batch_op.drop_column('city_id')

    op.drop_table('city')
    # ### end Alembic commands ###
