"""empty message

Revision ID: 938d513711ac
Revises: aa32017e57f4
Create Date: 2022-11-16 16:38:05.533784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '938d513711ac'
down_revision = 'aa32017e57f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ident', sa.String(length=6), nullable=True))

    with op.batch_alter_table('checkout_reservation', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_checkout_reservation_checkout_id'), ['checkout_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout_reservation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_checkout_reservation_checkout_id'), type_='unique')

    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.drop_column('ident')

    # ### end Alembic commands ###
