"""empty message

Revision ID: 9af7b8c48d40
Revises: e3fd61d9f829
Create Date: 2024-01-19 18:04:23.226447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9af7b8c48d40'
down_revision = 'e3fd61d9f829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update_logs', schema=None) as batch_op:
        batch_op.alter_column('created_at_datetime', new_column_name="created_at")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update_logs', schema=None) as batch_op:
        batch_op.alter_column('created_at', new_column_name="created_at_datetime")

    # ### end Alembic commands ###
