"""empty message

Revision ID: a1a91210100b
Revises: dc4f1e0eba83
Create Date: 2024-03-21 15:08:52.450033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a91210100b'
down_revision = 'dc4f1e0eba83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthday_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('birthplace', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('department_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('passport_identity', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('passport_issue_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('passport_issued_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('patronymic', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('surname', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.drop_column('surname')
        batch_op.drop_column('patronymic')
        batch_op.drop_column('passport_issued_by')
        batch_op.drop_column('passport_issue_date')
        batch_op.drop_column('passport_identity')
        batch_op.drop_column('department_code')
        batch_op.drop_column('birthplace')
        batch_op.drop_column('birthday_date')

    # ### end Alembic commands ###
