"""Удалит поля кэша и карты. Уберет таблицу расходов

Revision ID: a54b6d36e587
Revises: a54750996554
Create Date: 2024-05-14 19:31:46.963168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a54b6d36e587'
down_revision = 'a54750996554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkout_reservation')
    op.drop_table('checkout')
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.drop_column('cash')
        batch_op.drop_column('card')

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_column('cash')
        batch_op.drop_column('card')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('cash', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('cash', sa.INTEGER(), nullable=True))

    op.create_table('checkout',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sum', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_checkout')
    )
    op.create_table('checkout_reservation',
    sa.Column('checkout_id', sa.INTEGER(), nullable=True),
    sa.Column('reservation_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['checkout_id'], ['checkout.id'], name='fk_checkout_reservation_checkout_id_checkout'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservation.id'], name='fk_checkout_reservation_reservation_id_reservation'),
    sa.UniqueConstraint('checkout_id', name='uq_checkout_reservation_checkout_id')
    )
    # ### end Alembic commands ###
