"""empty message

Revision ID: a8e7dce831fc
Revises: d33e4ddb7b30
Create Date: 2023-06-16 15:21:45.844892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8e7dce831fc'
down_revision = 'd33e4ddb7b30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue_logs',
    sa.Column('log_id', sa.Integer(), nullable=True),
    sa.Column('queue_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['reservation_queue_view_log.id'], name='log_id'),
    sa.ForeignKeyConstraint(['queue_id'], ['reservation_queue.id'], name='queue_id')
    )
    op.drop_table('queue_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue_user',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('queue_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['queue_id'], ['reservation_queue.id'], name='queue_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_id')
    )
    op.drop_table('queue_logs')
    # ### end Alembic commands ###
