"""empty message

Revision ID: aa32017e57f4
Revises: adbbf50841c9
Create Date: 2022-11-16 13:12:29.239896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa32017e57f4'
down_revision = 'adbbf50841c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'redeemed', name='certificatestatusenum'), nullable=True),
    sa.Column('sum', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='author_id'),
    sa.ForeignKeyConstraint(['contact_id'], ['guest.id'], name='contact_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificate_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['certificate_id'])
        batch_op.create_foreign_key('certificate_id', 'certificate', ['certificate_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_constraint('certificate_id', type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('certificate_id')

    op.drop_table('certificate')
    # ### end Alembic commands ###
