"""empty message

Revision ID: b32e10ce3237
Revises: 96fc91f6e057
Create Date: 2023-04-19 15:08:27.001696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b32e10ce3237'
down_revision = '96fc91f6e057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue_room',
    sa.Column('queue_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['queue_id'], ['reservation_queue.id'], name='queue_id'),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name='room_id'),
    sa.UniqueConstraint('queue_id', name=op.f('uq_queue_room_queue_id'))
    )
    with op.batch_alter_table('reservation_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reservation_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('active', 'expired', 'reserved', 'canceled', name='queuestatusenum'), nullable=True))
        batch_op.create_foreign_key('reservation_id', 'reservation', ['reservation_id'], ['id'])
        batch_op.create_foreign_key('contact_id', 'guest', ['contact_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation_queue', schema=None) as batch_op:
        batch_op.drop_constraint('contact_id', type_='foreignkey')
        batch_op.drop_constraint('reservation_id', type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('reservation_id')
        batch_op.drop_column('contact_id')

    op.drop_table('queue_room')
    # ### end Alembic commands ###
