"""Удалит мусор из таблицы money

Revision ID: c0ba341738bc
Revises: c55724fbe692
Create Date: 2024-06-19 18:00:14.002264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0ba341738bc'
down_revision = 'c55724fbe692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('money', schema=None) as batch_op:
        batch_op.drop_column('all_by_card')
        batch_op.drop_column('income')
        batch_op.drop_column('expense')
        batch_op.drop_column('all_by_cash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('money', schema=None) as batch_op:
        batch_op.add_column(sa.Column('all_by_cash', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('expense', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('income', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('all_by_card', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
