"""Связь кассы и транзакций

Revision ID: c55724fbe692
Revises: 4e862d9fadf5
Create Date: 2024-06-19 14:50:20.692994

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c55724fbe692'
down_revision = '4e862d9fadf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cashier_transaction_dict',
                    sa.Column('cashier_id', sa.Integer(), nullable=True),
                    sa.Column('transaction_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['cashier_id'], ['money.id'], name='cashier_id'),
                    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], name='transaction_id'),
                    sa.UniqueConstraint('transaction_id', name=op.f('uq_cashier_transaction_dict_transaction_id'))
                    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cashier_transaction_dict')
    # ### end Alembic commands ###
