"""Связь кассы и транзакций

Revision ID: c55724fbe692
Revises: 4e862d9fadf5
Create Date: 2024-06-19 14:50:20.692994

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text, event
from sqlalchemy.engine import Engine
from sqlalchemy.orm import object_session

from models import Money, Transaction, Cinema, City
from sqlite_functions.get_shift_date import get_shift_date

# revision identifiers, used by Alembic.
revision = 'c55724fbe692'
down_revision = '4e862d9fadf5'
branch_labels = None
depends_on = None


def upgrade():
    @event.listens_for(Engine, "connect")
    def connect(dbapi_connection, _):
        dbapi_connection.create_function("get_shift_date", 3, get_shift_date)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cashier_transaction_dict',
                    sa.Column('cashier_id', sa.Integer(), nullable=True),
                    sa.Column('transaction_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['cashier_id'], ['money.id'], name='cashier_id'),
                    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], name='transaction_id'),
                    sa.UniqueConstraint('transaction_id', name=op.f('uq_cashier_transaction_dict_transaction_id'))
                    )
    # ### end Alembic commands ###
    session = None
    money = Money.query.all()

    for money_record in money:
        if not session:
            session = object_session(money_record)

        transactions = Transaction.query.join(Cinema).join(City).join(Money).filter(
            Transaction.cinema_id == money_record.cinema_id).filter(
            text("""date(get_shift_date("transaction".created_at, city.timezone, 0)) = :target""")).params(
            target=money_record.date).filter(Money.id == money_record.id).all()

        money_record.transactions = transactions
        session.add(money_record)

    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cashier_transaction_dict')
    # ### end Alembic commands ###
