"""Добавит автора к транзакциям

Revision ID: c8baa9b61842
Revises: a54b6d36e587
Create Date: 2024-05-16 13:55:52.175200

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c8baa9b61842'
down_revision = 'a54b6d36e587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer()))
        batch_op.create_foreign_key(batch_op.f('fk_transaction_author_id_user'), 'user', ['author_id'], ['id'])

    op.execute("""UPDATE "transaction" SET author_id = 2""")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transaction_author_id_user'), type_='foreignkey')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
