"""Добавит связь кинотеатра с терминалом сбп

Revision ID: d3935f203b2f
Revises: 177798ad5ad1
Create Date: 2024-05-14 13:45:43.263775

"""
from alembic import op
import sqlalchemy as sa

from models import Cinema, SbpTerminal

# revision identifiers, used by Alembic.
revision = 'd3935f203b2f'
down_revision = '177798ad5ad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sbp_terminal',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_sbp_terminal'))
                    )
    with op.batch_alter_table('cinema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sbp_terminal_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_cinema_sbp_terminal_id_sbp_terminal'), 'sbp_terminal',
                                    ['sbp_terminal_id'], ['id'])

    op.execute(sa.insert(SbpTerminal).values(id="ffc6b9622bb848499ae400613f6d0ee2"))
    op.execute(sa.insert(SbpTerminal).values(id="ebacccd4512f4d1f8a78b85fa87b5122"))
    op.execute(sa.insert(SbpTerminal).values(id="67bf8a1d73564a31a16651de1afe1943"))

    op.execute(sa.update(Cinema).where(Cinema.id == 1).values(sbp_terminal_id="ffc6b9622bb848499ae400613f6d0ee2"))
    op.execute(sa.update(Cinema).where(Cinema.id == 2).values(sbp_terminal_id="ebacccd4512f4d1f8a78b85fa87b5122"))
    op.execute(sa.update(Cinema).where(Cinema.id == 3).values(sbp_terminal_id="67bf8a1d73564a31a16651de1afe1943"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cinema', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cinema_sbp_terminal_id_sbp_terminal'), type_='foreignkey')
        batch_op.drop_column('sbp_terminal_id')

    op.drop_table('sbp_terminal')
    # ### end Alembic commands ###
