"""empty message

Revision ID: d5d4c3393343
Revises: c0ba341738bc
Create Date: 2024-06-25 17:01:55.910758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5d4c3393343'
down_revision = 'c0ba341738bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('money')
    op.drop_table('cashier_transaction_dict')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cashier_transaction_dict',
    sa.Column('cashier_id', sa.INTEGER(), nullable=True),
    sa.Column('transaction_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['cashier_id'], ['money.id'], name='cashier_id'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], name='transaction_id'),
    sa.UniqueConstraint('transaction_id', name='uq_cashier_transaction_dict_transaction_id')
    )
    op.create_table('money',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('cashier_start', sa.INTEGER(), nullable=False),
    sa.Column('cinema_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['cinema_id'], ['cinema.id'], name='cinema_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
