"""empty message

Revision ID: d65dda6778d3
Revises: 512b07381b4d
Create Date: 2022-12-28 10:51:59.106253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd65dda6778d3'
down_revision = '512b07381b4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cinema_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('cinema_id', 'cinema', ['cinema_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.drop_constraint('cinema_id', type_='foreignkey')
        batch_op.drop_column('cinema_id')

    # ### end Alembic commands ###
