"""empty message

Revision ID: dc4f1e0eba83
Revises: de6aa39dee2a
Create Date: 2024-01-31 16:56:49.264651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc4f1e0eba83'
down_revision = 'de6aa39dee2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_column('time')

    with op.batch_alter_table('reservation_queue', schema=None) as batch_op:
        batch_op.drop_column('start_time')
        batch_op.drop_column('date')
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.TIME(), nullable=False))

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.TIME(), nullable=False))

    # ### end Alembic commands ###
