"""empty message

Revision ID: de6aa39dee2a
Revises: 674d6e00c366
Create Date: 2024-01-29 18:24:26.546128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de6aa39dee2a'
down_revision = '674d6e00c366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', sa.DateTime()))
        batch_op.add_column(sa.Column('start_date', sa.DateTime()))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation_queue', schema=None) as batch_op:
        batch_op.drop_column('start_date')
        batch_op.drop_column('end_date')

    # ### end Alembic commands ###
