"""empty message

Revision ID: df1771fab60c
Revises: 5357cebb38e7
Create Date: 2023-04-20 13:03:35.770850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df1771fab60c'
down_revision = '5357cebb38e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_room', schema=None) as batch_op:
        batch_op.drop_constraint('uq_queue_room_queue_id', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_room', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_queue_room_queue_id', ['queue_id'])

    # ### end Alembic commands ###
