"""empty message

Revision ID: e1ccf1856e42
Revises: cdede9c4d9cd
Create Date: 2024-01-19 17:45:01.537337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1ccf1856e42'
down_revision = 'cdede9c4d9cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.alter_column('created_at_datetime', new_column_name="created_at")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.alter_column('created_at', new_column_name="created_at_datetime")

    # ### end Alembic commands ###
