"""empty message

Revision ID: e3fd61d9f829
Revises: 8c6a47edb3f2
Create Date: 2024-01-19 18:04:06.199993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3fd61d9f829'
down_revision = '8c6a47edb3f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update_logs', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('update_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
