"""empty message

Revision ID: ed1345651e7b
Revises: 11a1d418aa1b
Create Date: 2021-01-14 12:43:27.099141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed1345651e7b'
down_revision = '11a1d418aa1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_user', sa.Column('name', sa.String(length=40), nullable=True))
    op.add_column('admin_user', sa.Column('surname', sa.String(length=40), nullable=True))
    op.add_column('reservation', sa.Column('author', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'author')
    op.drop_column('admin_user', 'surname')
    op.drop_column('admin_user', 'name')
    # ### end Alembic commands ###
