"""empty message

Revision ID: ee1219dd368b
Revises: 510074d70f36
Create Date: 2024-01-19 17:34:59.126900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee1219dd368b'
down_revision = '510074d70f36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('created_at_datetime', new_column_name="created_at")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('created_at', new_column_name="created_at_datetime")

    # ### end Alembic commands ###
