"""empty message

Revision ID: f4fcd1bddfa6
Revises: b32e10ce3237
Create Date: 2023-04-19 15:09:56.815405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4fcd1bddfa6'
down_revision = 'b32e10ce3237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_another_reservation', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation_queue', schema=None) as batch_op:
        batch_op.drop_column('has_another_reservation')

    # ### end Alembic commands ###
