"""empty message

Revision ID: f9c0e8af2ff0
Revises: fc93d154b3f1
Create Date: 2023-06-05 19:23:05.014703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9c0e8af2ff0'
down_revision = 'fc93d154b3f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=120), nullable=True))

    # ### end Alembic commands ###
