from domains.reference import references_blueprint
from domains.reservation import reservations_blueprint
from domains.money import money_blueprint
from domains.certificate import certificate_blueprint
from domains.queue import queue_blueprint
from domains.base import base_blueprint
from domains.admin import admin_blueprint
from domains.user import user_blueprint
from domains.customer import customer_blueprint
